# Generated by Django 5.2.15 on 2026-06-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True, help_text='What was genuinely hard about it, and why?'),
        ),
        migrations.AddField(
            model_name='project',
            name='lessons_learned',
            field=models.TextField(blank=True, help_text='What would you do differently next time?'),
        ),
        migrations.AddField(
            model_name='project',
            name='outcome',
            field=models.TextField(blank=True, help_text='What happened once it was built or shipped?'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True, help_text='What problem was this solving, and for whom?'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, help_text='What did you actually build, and how?'),
        ),
    ]
