# Generated by Django 5.2.15 on 2026-06-28 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, help_text='Auto-filled from the title if left blank. Changing it after publishing breaks existing links and feed entries.', max_length=140, unique=True)),
                ('excerpt', models.CharField(help_text='Shown on the post list page and used as the RSS description.', max_length=240)),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to save a draft without it appearing on the site or in the RSS feed.')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Controls sort order and the date shown publicly. Editable — unlike created_at below, which is fixed the moment the row is created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
